title: Nestor Morales # your name (or website title) here
logo: "/images/cake.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Nice to have you here! Welcome to my portafolio website.
  <br><br>
  The aim of this website is to showcase my work as a robotics and software engineer. 
  <br><br>
  <a href="https://www.linkedin.com/in/nestoregon/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

